language: python
sudo: false
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  # - "3.7-dev"
  # - "nightly"
# command to install dependencies
install: "pip install https://github.com/neuropsychology/NeuroKit.py/zipball/master"
# command to run tests
install:
  - pip install codecov
  - pip install -r requirements.txt

script:
  - python setup.py install
  #- coverage run tests/test_statistics.py
  #- coverage run tests/test_miscellaneous.py
  #- coverage run tests/test_bio.py
  - coverage run tests/tests.py

after_success:
  - codecov
