language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6-dev" # 3.6 development branch
# command to install dependencies
install: "pip install https://github.com/neuropsychology/NeuroKit.py/zipball/master"
# command to run tests
script: nosetests
